Table users {
  id int [primary key, increment]
  login string [unique, not null]
  hash_password string [not null]
  created_at timestamp [not null, default: `now()`]
}

Table boards {
  id int [primary key, increment]
  creator_id int [not null, ref: > users.id]
  name string
  description string
  background_color string
  is_public boolean [default: false]
}

Table accesses {
  id int [primary key, increment]
  user_id int [not null, ref: > users.id]
  board_id int [not null, ref: > boards.id]
  
  indexes {
    (user_id, board_id) [unique]
  }
}

Table stickers {
  id int [primary key, increment]
  board_id int [not null, ref: > boards.id]
  x float [not null]
  y float [not null]
  layer_level int [not null]
  text string
  width float
  height float
}

