openapi: 3.0.3
info:
  title: Board Service API - Sharing
  description: API управления доступом к доскам для сервиса коллаборативных досок
  version: 1.0.0

servers:
  - url: https://api.boardservice.com/v1
    description: Production server

tags:
  - name: Sharing
    description: Управление доступом к доскам

paths:
  /boards/{boardId}/share:
    post:
      tags:
        - Sharing
      summary: Предоставление или обновление доступа к доске
      description: Выдача прав пользователю на доступ к доске. Если доступ уже существует, он будет обновлен.
      security:
        - bearerAuth: []
      parameters:
        - name: boardId
          in: path
          required: true
          description: ID доски
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - userLogin
                - permission
              properties:
                userLogin:
                  type: string
                  example: "user2@example.com"
                  description: Логин пользователя, которому предоставляется доступ
                permission:
                  type: string
                  enum: [view, edit]
                  example: "edit"
                  description: |
                    Уровень доступа:
                    - view: только просмотр
                    - edit: просмотр и редактирование
                    Примечание: owner определяется автоматически (создатель доски)
      responses:
        '200':
          description: Доступ успешно предоставлен
          content:
            application/json:
              schema:
                type: object
                properties:
                  boardId:
                    type: integer
                    example: 1
                  userId:
                    type: integer
                    example: 2
                  permission:
                    type: string
                    enum: [view, edit]
                    example: "edit"
                  grantedAt:
                    type: string
                    format: date-time
                    example: "2024-01-15T10:30:00Z"
                  grantedBy:
                    type: integer
                    example: 1
                    description: ID пользователя, предоставившего доступ
        '400':
          description: Некорректные данные
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Не авторизован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Нет прав на управление доступом
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Доска или пользователь не найдены
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    get:
      tags:
        - Sharing
      summary: Получение списка пользователей с доступом
      description: Получение списка всех пользователей, имеющих доступ к доске
      security:
        - bearerAuth: []
      parameters:
        - name: boardId
          in: path
          required: true
          description: ID доски
          schema:
            type: integer
      responses:
        '200':
          description: Список пользователей успешно получен
          content:
            application/json:
              schema:
                type: object
                properties:
                  boardId:
                    type: integer
                    example: 1
                  shares:
                    type: array
                    items:
                      $ref: '#/components/schemas/ShareInfo'
        '401':
          description: Не авторизован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Нет доступа к доске
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Доска не найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - Sharing
      summary: Отзыв доступа к доске
      description: Удаление прав пользователя на доступ к доске
      security:
        - bearerAuth: []
      parameters:
        - name: boardId
          in: path
          required: true
          description: ID доски
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - userLogin
              properties:
                userLogin:
                  type: string
                  example: "user2@example.com"
                  description: Логин пользователя, у которого отзывается доступ
      responses:
        '204':
          description: Доступ успешно отозван
        '401':
          description: Не авторизован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Нет прав на управление доступом
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Доска, пользователь или доступ не найдены
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT токен, полученный при входе/регистрации

  schemas:
    Error:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          example: "VALIDATION_ERROR"
          description: Код ошибки
        message:
          type: string
          example: "Некорректные данные запроса"
          description: Человекочитаемое описание ошибки
        details:
          type: object
          description: Дополнительная информация об ошибке

    ShareInfo:
      type: object
      properties:
        userId:
          type: integer
          example: 2
        userLogin:
          type: string
          example: "user2@example.com"
        permission:
          type: string
          enum: [view, edit]
          example: "edit"
          description: |
            Уровень доступа:
            - view: только просмотр
            - edit: просмотр и редактирование
            Примечание: owner определяется автоматически (создатель доски)
        grantedAt:
          type: string
          format: date-time
          example: "2024-01-15T10:30:00Z"
